<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Hospital [
	<!ELEMENT Hospital (location, medicalSpecialization, Orders)>
	<!ATTLIST Hospital hospitalID CDATA #REQUIRED name CDATA #REQUIRED>
	<!ELEMENT location (#PCDATA)>
	<!ELEMENT medicalSpecialization (#PCDATA)>
	<!ELEMENT Orders (Order*)>
	<!ELEMENT Order (totalAmountInstruments, orderDate, deliveryDate)>	
	<!ATTLIST Order orderID CDATA #REQUIRED>
	<!ELEMENT totalAmountInstruments (#PCDATA)>
	<!ELEMENT orderDate (#PCDATA)>
	<!ELEMENT deliveryDate (#PCDATA)>
]>
<Hospital hospitalID="3" name="asdf">
    <location>wer</location>
    <medicalSpecialization>ert</medicalSpecialization>
    <Orders>
        <Order orderID="2">
            <totalAmountInstruments>345</totalAmountInstruments>
            <orderDate>2000-10-05</orderDate>
            <deliveryDate>2000-10-05</deliveryDate>
        </Order>
    </Orders>
</Hospital>